force-app/main/default/objects/Setup_Assistant_Data__c/Setup_Assistant_Data__c.object-meta.xml
<CustomObject>
    <label>Setup Assistant Data</label>
    <nameField>
        <label>Setup Assistant Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Setup Assistant Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Setup_Assistant_Data__c/fields/Donation_Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Donation_Stage_Name__c</fullName>
    <label>Donation Stage Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Setup_Assistant_Data__c/fields/Refund_Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Refund_Stage_Name__c</fullName>
    <label>Refund Stage Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Setup_Assistant_Data__c/fields/Steps_Completed__c.field-meta.xml
<CustomField>
    <fullName>Steps_Completed__c</fullName>
    <label>Steps Completed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/setupAssistant.cls
public with sharing class setupAssistant {
    @AuraEnabled
    public static String getData() {
        responseData response = new responseData();

        try {
            List<String> fields = new List<String>();

            for (Schema.SObjectField field : Setup_Assistant_Data__c.sObjectType.getDescribe().fields.getMap().values()) {
                fields.add(field.getDescribe().getName());
            }

            List<SObject> data = Database.query('SELECT ' + String.join(fields, ',') + ' FROM ' + constants.NAMESPACE_API + 'Setup_Assistant_Data__c WHERE Name = \'Default\'');
            if (data.isEmpty()) {
                response.put('data', new Setup_Assistant_Data__c(
                    Steps_Completed__c = 0,
                    Donation_Stage_Name__c = 'Closed Won',
                    Refund_Stage_Name__c = 'Closed Lost'
                ));
            } else {
                response.put('data', data[0]);
            }
        } catch (Exception e) {
            response.addError(e.getMessage());
        }

        return response.getJsonString();
    }

    @AuraEnabled
    public static String saveData(String data) {
        responseData response = new responseData();

        try {
            Map<String, Object> dataMap = (Map<String, Object>)JSON.deserializeUntyped(data);

            Setup_Assistant_Data__c dataObj = (Setup_Assistant_Data__c)utilities.getSobjectByMap(dataMap, constants.NAMESPACE_API + 'Setup_Assistant_Data__c');
            dataObj.Name = 'Default';

            upsert dataObj;

            response.put('data', dataObj);
        } catch (Exception e) {
            response.addError(e.getMessage());
        }

        return response.getJsonString();
    }
}